{{- if .Values.cnpg.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "recipie.db.name" . }}
  labels:
    {{- include "recipie.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  instances: {{ .Values.cnpg.instances }}
  imageName: {{ .Values.cnpg.imageName }}
  bootstrap:
    initdb:
      database: {{ .Values.cnpg.database }}
      owner: {{ .Values.cnpg.owner }}
      secret:
        name: {{ include "recipie.db.appSecretName" . }}
  storage:
    size: {{ .Values.cnpg.storage.size }}
    {{- with .Values.cnpg.storage.storageClass }}
    storageClass: {{ . }}
    {{- end }}
{{- end }}
