apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "recipie.docs.fullname" . }}
  labels:
    {{- include "recipie.labels" . | nindent 4 }}
    app.kubernetes.io/component: docs
spec:
  replicas: {{ .Values.docs.replicaCount }}
  selector:
    matchLabels:
      {{- include "recipie.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: docs
  template:
    metadata:
      labels:
        {{- include "recipie.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: docs
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.docs.image.repository }}:{{ .Values.docs.image.tag }}"
          imagePullPolicy: {{ .Values.docs.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          resources:
            {{- toYaml .Values.docs.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "recipie.docs.fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "recipie.docs.fullname" . }}
  labels:
    {{- include "recipie.labels" . | nindent 4 }}
    app.kubernetes.io/component: docs
spec:
  type: ClusterIP
  selector:
    {{- include "recipie.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: docs
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
