{{- if .Values.rustfs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "recipie.rustfs.fullname" . }}
  labels:
    {{- include "recipie.labels" . | nindent 4 }}
    app.kubernetes.io/component: rustfs
spec:
  type: ClusterIP
  selector:
    {{- include "recipie.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rustfs
  ports:
    - name: s3
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: console
      port: 9001
      targetPort: 9001
      protocol: TCP
{{- end }}
