apiVersion: v1
kind: Service
metadata:
  name: {{ include "recipie.fullname" . }}-backend
  labels:
    {{- include "recipie.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "recipie.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
