site_name: Recipie Docs
site_url: https://docs.domain.com
site_description: Documentation for the Recipie app

theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - Home: index.md

plugins:
  - search
